# Pytorch Basics exploring

In [1]:
import torch

x = torch.tensor(1.0)
w = torch.tensor(2.0, requires_grad=True)
b = torch.tensor(3.0, requires_grad=True)

y = w * x + b
y.backward()

### Usage of DataLoader and DataSet classes

Example of iterating numpy array using dataloader. It also works with python list and tensors

In [2]:
import numpy as np
arr = np.array([1,2,3,4,5,6])

from torch.utils.data import DataLoader

t = DataLoader(arr,batch_size=3)
for item in t:
    print(item)

tensor([1, 2, 3])
tensor([4, 5, 6])


Example of combining x and y  into single class

In [3]:
from torch.utils.data import Dataset

torch.manual_seed(1)

x = torch.rand(4,3)
y = torch.rand(4)

class JointData(Dataset):
    def __init__(self,x,y):
        self.x , self.y = x , y

    def __getitem__(self,idx):
        return self.x[idx], self.y[idx]

    def __len__(self):
        return len(self.x)

dataset = JointData(x,y)

for items in DataLoader(dataset,batch_size=2):
    print(items)

[tensor([[0.7576, 0.2793, 0.4031],
        [0.7347, 0.0293, 0.7999]]), tensor([0.6826, 0.3051])]
[tensor([[0.3971, 0.7544, 0.5695],
        [0.4388, 0.6387, 0.5247]]), tensor([0.4635, 0.4550])]


### Build the Neural Network


In [28]:
import torch
from torch import nn

class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()

        self.flatten = nn.Flatten()
        self.linear = nn.Sequential(
            nn.Linear(28*28,512),
            nn.ReLU(),
            nn.Linear(512,512),
            nn.ReLU(),
            nn.Linear(512,10),
            nn.Softmax(dim=1)
        )

    def forward(self,x):
        
        x = self.flatten(x)
        x = self.linear(x)
        return x
    
model = NeuralNetwork()
model

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
    (5): Softmax(dim=1)
  )
)

In [42]:
x = torch.rand(1,28,28)
y = model(x)
y

tensor([[0.0950, 0.0995, 0.0991, 0.0991, 0.0975, 0.0991, 0.0944, 0.1005, 0.1111,
         0.1046]], grad_fn=<SoftmaxBackward0>)