## Linear Regression model

In [6]:
# generate numpy array from 1 to 10
import numpy as np
x_train = np.arange(1, 11).astype('float32')
y_train = np.array([1.0, 1.3, 3.1, 2.0, 5.0, 6.3, 6.6, 
                    7.4, 8.0, 9.0], dtype='float32')

# import ploty and plot the data
import plotly.graph_objects as go
fig = go.Figure(data=[go.Scatter(x=x_train, y=y_train)])
fig.show()

In [13]:
import torch
from torch.utils.data import TensorDataset, DataLoader

train_set = TensorDataset(torch.from_numpy(x_train),torch.from_numpy(y_train))

for x , y in DataLoader(train_set):
    print(f"{x} : {y}")
    

tensor([1.]) : tensor([1.])
tensor([2.]) : tensor([1.3000])
tensor([3.]) : tensor([3.1000])
tensor([4.]) : tensor([2.])
tensor([5.]) : tensor([5.])
tensor([6.]) : tensor([6.3000])
tensor([7.]) : tensor([6.6000])
tensor([8.]) : tensor([7.4000])
tensor([9.]) : tensor([8.])
tensor([10.]) : tensor([9.])


In [3]:
torch.manual_seed(1)
weights = torch.randn(1, requires_grad=True)
bias = torch.randn(1, requires_grad=True)

for epoch in range(10):
    for x , y in DataLoader(train_set):
        output = x @ weights + bias

        loss = (output - y).pow(2).sum()
        loss.backward()

        # wieghts are updated on every prediction
        with torch.no_grad():
            weights -= 0.01 * weights.grad
            bias -= 0.01 * bias.grad   
            weights.grad.zero_()
            bias.grad.zero_()

    print(f"epoch: {epoch} | loss: {loss}") 

print(weights, bias)

epoch: 0 | loss: 0.10559078305959702
epoch: 1 | loss: 0.10485699772834778
epoch: 2 | loss: 0.10415038466453552
epoch: 3 | loss: 0.10347193479537964
epoch: 4 | loss: 0.1028183251619339
epoch: 5 | loss: 0.1021881252527237
epoch: 6 | loss: 0.10158417373895645
epoch: 7 | loss: 0.10100141167640686
epoch: 8 | loss: 0.10044027864933014
epoch: 9 | loss: 0.09990180283784866
tensor([0.9168], requires_grad=True) tensor([0.1540], requires_grad=True)


In [4]:
# gnerate test data
x_test = np.linspace(0, 9, num=10, dtype='float32').reshape(-1, 1)
x_test_tensor = torch.from_numpy(x_test)

# make predictions
y_test = x_test_tensor @ weights + bias

y_test = y_test.detach().numpy()
print(y_test)
x_test = x_test.reshape(1,-1)[0]
print(x_test)

# plot test and train data
fig = go.Figure(data=[go.Scatter(x=x_test, y=y_test)])
fig.add_scatter(x=x_train, y=y_train)
fig.show()



[0.15395285 1.070797   1.987641   2.904485   3.821329   4.7381735
 5.6550174  6.5718617  7.4887056  8.405549  ]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


## Using built in loss and optimizers of pytorch

In [5]:
from ast import mod
import torch.nn as nn

model = nn.Linear(1,1) 
loss = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

for epoch in range(10):
    for x , y in DataLoader(train_set):
        output = model(x)

        loss_value = loss(output, y)
        loss_value.backward()
        optimizer.step()
        optimizer.zero_grad()

    print(f"epoch: {epoch} | loss: {loss_value}")

print(f'Final weights: {model.weight}, bias: {model.bias}')

epoch: 0 | loss: 0.10727459192276001
epoch: 1 | loss: 0.10647644847631454
epoch: 2 | loss: 0.10570795834064484
epoch: 3 | loss: 0.1049700528383255
epoch: 4 | loss: 0.10426060110330582
epoch: 5 | loss: 0.10357564687728882
epoch: 6 | loss: 0.10291925817728043
epoch: 7 | loss: 0.10228630900382996
epoch: 8 | loss: 0.10167720913887024
epoch: 9 | loss: 0.10109175741672516
Final weights: Parameter containing:
tensor([[0.9137]], requires_grad=True), bias: Parameter containing:
tensor([0.1872], requires_grad=True)
