Linear Regression 

In [1]:
# generate numpy array from 1 to 10
import numpy as np
x = np.arange(1, 11)
y = np.array([1.0, 1.3, 3.1, 2.0, 5.0, 6.3, 6.6, 
                    7.4, 8.0, 9.0], dtype='float32')

# import ploty and plot the data
import plotly.graph_objects as go
fig = go.Figure(data=[go.Scatter(x=x, y=y)])
fig.show()

In [3]:
import torch
from torch.utils.data import TensorDataset, DataLoader

train_set = TensorDataset(torch.from_numpy(x),torch.from_numpy(y))

for x , y in DataLoader(train_set):
    print(f"{x} : {y}")
    

tensor([1]) : tensor([1.])
tensor([2]) : tensor([1.3000])
tensor([3]) : tensor([3.1000])
tensor([4]) : tensor([2.])
tensor([5]) : tensor([5.])
tensor([6]) : tensor([6.3000])
tensor([7]) : tensor([6.6000])
tensor([8]) : tensor([7.4000])
tensor([9]) : tensor([8.])
tensor([10]) : tensor([9.])
